AllCops:
  TargetRubyVersion: 2.3

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# I like Puppet hash behavior
Style/TrailingCommaInLiteral:
  Enabled: false

# Not until RubyMine learns to indent these properly
Style/MultilineMethodCallIndentation:
  Enabled: false
